Add individual padding attributes for the cell and message labels
MessageKit/MessageKit pull request #1118
Opened 2019-06-27 22:41 UTC by mdescalzo

What does this implement/fix? Explain your changes.
---------------------------------------------------
- Adds `cellTopLabelPadding`, `cellBottomLabelPadding`, `messageTopLabelPadding`, & `messageBottomLabelPadding` attributes to `MessagesCollectionViewLayoutAttributes`
- Adds the above attributes to layout calculations in `MessageSizeCalculator`
- Adds `cellTopLabelPadding`, `cellBottomLabelPadding`, `messageTopLabelPadding`, & `messageBottomLabelPadding` methods to the `MessageLayoutDelegate` protocol with defaults which return `.zero` insets.

This allows manipulation of the label frames which can be desirable when adding borders or backgrounds to these labels.

The default `.zero` insets means this should not break/change existing layout behavior.

Does this close any currently open issues?
------------------------------------------
This is, in part, to address issues discussed in #1107 

Any relevant logs, error output, etc?
-------------------------------------
nope

Any other comments?
-------------------
nope

Where has this been tested?
---------------------------
**Devices/Simulators:** 
iPad sim, iPhone Xs, iPad mini

**iOS Version:** …
12.2

**Swift Version:** …
4.2 & 5

**MessageKit Version:**
3.0.0

2019-06-28 03:44 UTC, nathantannar4 requested changes
I'm happy to add padding properties, but it should follow the same convention we have for the other layout attributes.

2019-06-28 03:44 UTC, nathantannar4 commented on Sources/Protocols/MessagesLayoutDelegate.swift
> +    func cellTopLabelPadding(for message: MessageType, at indexPath: IndexPath) -> UIEdgeInsets {
We cannot set these properties through a delegate method. See #1107

2019-06-28 03:44 UTC, nathantannar4 commented on Sources/Layout/MessagesCollectionViewLayoutAttributes.swift
> +    public var cellTopLabelPadding: UIEdgeInsets = .zero
This is where we want the padding properties, so its confusing how there is a mixture of this and delegates. We should also have a convenience setter in `MessagesCollectionViewFlowLayout` to set this as we do with the other properties

2019-07-01 17:06 UTC, mdescalzo commented
I'm pulling this back for a rework.  Thank you very much for the input.

2019-07-01 17:06 UTC, closed without merging

2019-07-01 17:51 UTC, nathantannar4 commented
Look forward to the new version!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>