Support Swift Package Manager
MessageKit/MessageKit pull request #1239
Opened 2020-01-29 17:00 UTC by Nixon506E

2020-02-17 04:30 UTC, hyouuu commented
@zhongwuzw @SD10 @nathantannar4  could you take a look at PRs? Or maybe add a few members to keep this project alive?

2020-02-17 04:36 UTC, zhongwuzw commented
@hyouuu Hey, sorry we don't have much time on it, would u want to collaborate to help us? or any members you can recommend?

2020-02-17 04:37 UTC, hyouuu commented
Yes I would love to at least do PR reviews so the community can help move it forward :)

2020-02-17 04:37 UTC, hyouuu commented
Didn't pay close attention to contributions but you could look into PR submission etc to see who would be the best candidates

2020-02-17 04:45 UTC, zhongwuzw commented
> Yes I would love to at least do PR reviews so the community can help move it forward :)

I added you and @moldovaniosif write permission of master, please help us to move on. :)

2020-02-17 05:53 UTC, hyouuu commented
Nice thanks!

2020-02-17 06:16 UTC, hyouuu commented
@zhongwuzw would you be able to grant access to circle so I can re-run test for https://github.com/MessageKit/MessageKit/pull/1189

2020-02-18 22:15 UTC, hyouuu commented on Package.swift
> +        .package(url: "https://github.com/Nixon506E/InputBarAccessoryView.git", from: "4.2.1")
Saw your branch is 2 commits ahead - assuming you'll keep it updated :)

2020-02-18 22:15 UTC, hyouuu commented on Package.resolved
> +        "package": "RxSwift",
Do we actually use RxSwift in MessageKit?

2020-02-19 16:41 UTC, Kaspik commented on Package.resolved
> +        "package": "RxSwift",
Soo, that's something we should talk about and take action asap - there is RxSwift dependency for InputBarAccessory but I believe it's wrong.

2020-02-22 04:53 UTC, Kaspik requested changes

2020-02-22 04:53 UTC, Kaspik commented on Package.swift
> +        .package(url: "https://github.com/Nixon506E/InputBarAccessoryView.git", from: "4.2.1")
Please open PR to the original repo - this can't be merged I believe.

2020-02-22 04:53 UTC, Kaspik commented on Package.resolved
> +        "package": "RxSwift",
RxSwift should be taken away and aded as an optional dependency / extension.

2020-02-22 04:53 UTC, Kaspik commented
Also please point to the `development` branch, not master.

2020-03-26 20:39 UTC, radugrinico commented
@austinwright , Can we get this PR merged? Really need this feature.

2020-03-26 20:41 UTC, Kaspik commented
We can't yet, it's not even up-to-date, as well as we should split this and RxSwift extension so people with SPM don't hve Rx included.

2020-03-28 16:56 UTC, radugrinico commented
@Kaspik, Can I help to speed up the process?

2020-03-29 17:17 UTC, Kaspik commented
@xcodefriend It would be nice to find a way how to have RxMessageKit split out of main project with main project as a dependency, so we can have separate Package file for that and separate for main project without RxExtensions completely. What do you think?
(SPM doesn't have support for "subspec" kind of things so Rx would be always included even for people without that - that's why we need to make these changes)

2020-04-29 08:47 UTC, Kaspik commented
Closing in favor of https://github.com/MessageKit/MessageKit/pull/1341.

2020-04-29 08:47 UTC, closed without merging