Bug fix/long message label issue72
MessageKit/MessageKit pull request #136
Opened 2017-09-19 14:27 UTC by Summa-Labs

2017-09-19 14:40 UTC, Sherlouk requested changes
Couple minors, haven't had a chance to run it fully yet to ensure it actually works!

Also woo for first time contributor! Welcome!

2017-09-19 14:40 UTC, Sherlouk commented on Sources/MessagesViewController.swift
> +			messagesCollectionView.contentOffset = CGPoint(x: 0, y: messagesCollectionView.contentSize.height-messagesCollectionView.frame.height+50)
Indentation, and where has this 50 come from?

2017-09-19 14:40 UTC, Sherlouk commented on Sources/MessageLabel.swift
> +		self.font = UIFont.defaultMessageLabelFont()
Indented a bit too far!

2017-09-19 14:40 UTC, Sherlouk commented on Sources/UIFont+Extensions.swift
> +//
Copyright header needs replacing

2017-09-19 14:49 UTC, SD10 commented
@Summa-Labs The real issue is I forgot to apply the font in: `apply(_ layoutAttributes: UICollectionViewLayoutAttributes)` 😅 

If you want to make this patch on the `enhance/media-messages` branch for `TextMessageCell` you're welcome to.

2017-09-20 19:33 UTC, SD10 commented
@Summa-Labs Thank you for finding this bug I will take care of it 👍

2017-09-20 19:33 UTC, closed without merging