Changed right inset for outgoingMessageBottomLabelAlignment
MessageKit/MessageKit pull request #1567
Opened 2021-04-01 14:59 UTC by Turkey-man

Changed right inset for outgoingMessageBottomLabelAlignment to 4 in MessageSizeCalculator. With previous value 42 the right alignment for messageBottomLabel didn't work correctly.

What does this implement/fix? Explain your changes.
---------------------------------------------------

I changed right inset for outgoingMessageBottomLabelAlignment to 4 in MessageSizeCalculator. With previous value 42 the right alignment for messageBottomLabel didn't work correctly.

Does this close any currently open issues?
------------------------------------------
The issue was closed in 2018, but the solution provided didn't work today.

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
No.

Where has this been tested?
---------------------------
**Devices/Simulators:**
iPhone 11 Pro simulator
**iOS Version:** 
14.4
**Swift Version:** 
5.3
**MessageKit Version:** 
3.5.1

2021-04-02 13:49 UTC, Kaspik commented
Could you please add screenshot before and after and mark what has changed?

2021-04-02 13:49 UTC, Kaspik requested changes
Will need also changelog entry please :)

2021-04-02 15:00 UTC, Turkey-man commented
Hello. As you can see from the screenshots attached to my response, right text alignment hasn't worked correctly with the value of right inset set to 42 for outgoingMessageBottomLabelAlignment.

02 квітня 2021, 16:49:22, від "Jakub Kašpar" ***@***.***>:



Could you please add screenshot before and after and mark what has changed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-02 19:45 UTC, Kaspik commented
Not seeing any screenshots unfortunately. 😞

2021-04-06 12:38 UTC, Turkey-man commented
Before:

After:

02 квітня 2021, 22:46:07, від "Jakub Kašpar" ***@***.***>:



Not seeing any screenshots unfortunately. 😞

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-06 13:29 UTC, Kaspik commented
Still nothing. :)

2021-04-07 14:36 UTC, Turkey-man commented
Even now?
<img width="160" alt="Alignment before" src="https://user-images.githubusercontent.com/18172342/113884513-b243b580-97c7-11eb-9d32-12ef605cf329.png">
<img width="115" alt="Alignment after" src="https://user-images.githubusercontent.com/18172342/113884506-b1ab1f00-97c7-11eb-8bfa-07c52259a2a0.png">

2021-04-07 14:37 UTC, Kaspik approved these changes

2021-04-07 14:37 UTC, Kaspik commented
Just add a changelog entry please.

2021-04-07 14:38 UTC, Turkey-man commented
How do I do that?

07 квітня 2021, 17:38:01, від "Jakub Kašpar" ***@***.***>:



Just add a changelog entry please.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-07 14:39 UTC, Kaspik commented
Add info about this pr to "Changelog.md" in this repo and push to this PR

2021-04-07 16:01 UTC, Turkey-man commented
Just pushed.

2021-04-12 18:41 UTC, Kaspik approved these changes

2021-04-12 18:42 UTC, Kaspik commented
@Turkey-man PR needs rebase / merge master please. :)

2021-04-15 11:00 UTC, Turkey-man commented
How do I do that? My current branch is master already.

2021-04-21 11:49 UTC, Kaspik commented
You need to merge in the master branch from MessageKit

2021-06-29 04:12 UTC, ThomasWDev commented
PR has been open too long.

2021-09-10 09:27 UTC, Kaspik commented
@Turkey-man Are you planning to merge the master in?

2021-12-14 18:18 UTC, wiarabeauty commented
Hello, is it possible to merge this fix from this issue? I am currently facing it in my project.
Thank you @Kaspik

2021-12-14 19:34 UTC, Kaspik commented
I'm not able to make it updated, but feel free to create new PR with the fix.

2022-02-03 15:40 UTC, martinpucik commented
The inset is there to accommodate avatar view for outgoing messages. To change this in your project, you should subclass `MessageSizeCalculator` and override override `outgoingMessageBottomLabelAlignment` there. Hope this helps 🤞

2022-02-03 15:40 UTC, closed without merging