Added a top UIStackView to MessageInputBar
MessageKit/MessageKit pull request #194
Opened 2017-09-29 08:03 UTC by nathantannar4

This is to support features like @mention and a typing indicator. Updated the Example to show changes.

There are some **breaking changes** but only with the backgroundView of the MessageInputBar to support difference background colors behind the top stack view and main content

2017-09-29 08:17 UTC, SD10 commented
I don't mind adding another `UIStackView` but something doesn't feel right about having the typing indicator inside of the `MessageInputBar`. I really don't want these two components coupled 😕

The interaction between the keyboard/message input bar and the collectionview is already really painful. I'm not sure I want to add more state management to the part of the library.

Let's leave this open and see what others think.

2017-09-30 02:07 UTC, SD10 commented on Sources/MessageInputBar.swift
> +            } else if !isTranslucent {
It's probably best just to add this once if they set`isTranslucent` to `true`

2017-09-30 02:07 UTC, SD10 commented on Sources/MessageInputBar.swift
> +    open let typingIndicatorLabel = UILabel()
We need to remove this as we discussed

2017-09-30 02:08 UTC, SD10 requested changes
Let's just leave the top stack view and I think this is good :P

2017-10-03 01:37 UTC, nathantannar4 commented
Sorry I accidentally committed a merge to this PR. Its for autocomplete

2017-10-03 02:38 UTC, SD10 commented
No worries 😃 I know the `MessageInputBar` is your jam but I really need to limit what goes into `v0.9.0`. This is also ~500 lines of code now so it can become difficult for me to review. Let's try and push enhancements of the `MessageInputBar` until after `v0.9.0`. Bugfixes are welcome any time

2017-10-04 23:48 UTC, closed without merging

2021-07-27 13:51 UTC, ohazar commented
Hello, what is the status of this change? Is it going to be added or canceled? Ticket looks "closed" but its label is "in progress".