[Fixed] iPhone X inputAccessoryView layout issue
MessageKit/MessageKit pull request #209
Opened 2017-10-01 05:05 UTC by SD10

### TODO:
- [ ] CHANGELOG entry

Not sure if this is expected behavior for inputAccessoryView. Looks like there is a radar here:
http://www.openradar.me/34411433

The view background color is set to the color of the `MessageInputBar`

2017-10-01 07:09 UTC, nathantannar4 commented
I can't believe apple didn't add native support for this so we don't have to

2017-10-01 07:15 UTC, nathantannar4 requested changes
With the changes i made in my latest PR the color you will need is: messageInput.backgroundView.backgroundColor

2017-10-01 09:06 UTC, alexbinary commented on Sources/MessagesViewController.swift
> +            bottom = messagesCollectionView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor)
I believe `view.layoutMarginsGuide.bottomAnchor` would work as well.

`layoutMarginsGuide` is available since iOS 9.

2017-10-01 09:08 UTC, alexbinary commented on Sources/MessageInputBar.swift
> +    // Could be fixed by Apple soon
I don't think this is a bug. See my answer on the SO post for a cleaner fix.

2017-10-01 17:55 UTC, nathantannar4 commented
I notice that when adding those constraints it breaks stuff. Another option is to increase the bottom padding and then reduce it when the keyboard becomes the first responder

2017-10-01 18:53 UTC, SD10 commented
I don't like any of this to be honest lol. Supporting the iPhone Notch is low priority to me this weekend :/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2017-10-01 19:43 UTC, etoledom commented
@nathantannar4 @SD10 Try this:

If you change the line 280 on MessageInputBar.swift to:
`bottom: bottomStackView.bottomAnchor.constraint(equalTo: layoutMarginsGuide.bottomAnchor, constant: -padding.bottom),`
The inputView seems to be in the correct position for the iPhone X.
Is not the definitive answer since the collectionView bottom inset is still wrong, but I think this could be a better start.

The change would be to pin the lower subview of MessageInputBar to `layoutMarginsGuide.bottomAnchor` instead to the `.bottomAnchor`

2017-10-01 19:47 UTC, etoledom commented
![simulator screen shot - iphone2017-c - 2017-10-01 at 16 46 26](https://user-images.githubusercontent.com/9772967/31058312-2683c84e-a6c8-11e7-994b-3b4b61e0ec26.png)

2017-10-04 12:36 UTC, etoledom commented
Anything new about this? I could check it more in detail

2017-10-04 14:20 UTC, SD10 commented
@etoledom Be my guest 👍 To be honest, I haven't read through everything here in great detail. Other more pressing issues taking precedence

2017-10-18 06:39 UTC, closed without merging