- added open var scrollsToBottomOnFirstLayout
MessageKit/MessageKit pull request #213
Opened 2017-10-02 15:02 UTC by FraDeliro

- Added open var scrollsToBottomOnFirstLayout, if true messagesCollectionView scrollToBottom
#183

2017-10-02 18:31 UTC, SD10 commented on Sources/MessagesViewController.swift
> +            guard scrollsToBottomOnFirstLayout == true else {
Can we just make this read as:
```Swift
if scrollsToBottomOnFirstLayout {
    messagesCollectionView.scrollsToBottom(animated: false)
}
```

2017-10-02 18:32 UTC, SD10 commented on Sources/MessagesViewController.swift
> +            scrollsToBottomOnFirstLayout = false
let's not modify the bool after we scroll to bottom, all we're really concerned with is the `isFirstLayout` flag

2017-10-02 18:34 UTC, SD10 requested changes
@FraDeliro Thanks for taking care of this 💯 Just a few nit revisions. Can you also add a CHANGELOG entry matching the same style we are using in the `v0.9.0` branch CHANGELOG? This would go under **added** and is not a breaking change

2017-10-02 23:47 UTC, SD10 approved these changes
@FraDeliro Thank you for taking care of this for us 👍

2017-10-02 23:47 UTC, merged

2017-10-03 08:52 UTC, FraDeliro commented
@SD10 Thanks for your library ;)

2019-01-27 23:27 UTC, fishcharlie commented
What is the status of this? This code doesn't look to be in the library currently.