Adding copy/paste support from MessagesViewController
MessageKit/MessageKit pull request #248
Opened 2017-10-09 10:02 UTC by Ganzolo

(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

What does this implement/fix? Explain your changes.
---------------------------------------------------
Copy implementation

Does this close any currently open issues?
------------------------------------------
#143 

Any other comments?
-------------------
Better implementation

2017-10-09 18:27 UTC, SD10 commented on Sources/Controllers/MessagesViewController.swift
> +		self.addMenuControllerObservers()
Can we remove `self` here?

2017-10-09 18:28 UTC, SD10 commented on Sources/Views/MessageLabel.swift
> -        let longPressGesture = UILongPressGestureRecognizer(target: self, action: #selector(handleGesture(_:)))
I still have to look into this

2017-10-09 18:28 UTC, SD10 commented on Sources/Controllers/MessagesViewController.swift
> +	public func collectionView(_ collectionView: UICollectionView, shouldShowMenuForItemAt indexPath: IndexPath) -> Bool {
This needs to be marked as `open`

2017-10-09 18:29 UTC, SD10 commented on Sources/Controllers/MessagesViewController.swift
> +	public func collectionView(_ collectionView: UICollectionView, canPerformAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?) -> Bool {
This needs to be marked as `open`

2017-10-09 18:29 UTC, SD10 commented on Sources/Controllers/MessagesViewController.swift
> +	public func collectionView(_ collectionView: UICollectionView, performAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?) {
This needs to be marked as `open`

2017-10-09 18:29 UTC, SD10 commented on Sources/Controllers/MessagesViewController.swift
> +	fileprivate var targetedFrame = CGRect.zero
Can we keep properties at the top of the file like we're doing with the rest of them?

2017-10-09 18:31 UTC, SD10 requested changes
Thanks @Ganzolo 👍 I just have to review the `Long Press Gesture` and any other gesture conflicts. I left you some comments regarding how I think we should organize the code

2017-10-10 09:09 UTC, Ganzolo commented
@SD10 Thanks for feedbacks. I did all suggested fixes. I have nothing to say about what u suggested, except for putting all properties at the top. I usually like to put them close to methods that are using it so refactoring is easier, scope is more concise. 

However, then we cannot use extensions which is also a good way to break the code. So both solution is fine with me. The best would be to be able to add properties in an extension :)

2017-10-17 01:36 UTC, SD10 commented
@Ganzolo Can you add a CHANGELOG entry for this?

2017-10-20 21:25 UTC, nathantannar4 commented
I like this!

2017-10-20 21:27 UTC, SD10 commented
Me too, I just have to make sure the gestures are behaving properly. If either of you can pull it and run it that would be great. I will try myself again soon.

I think there was some inconsistency with the gestures last time I tested it. Sometimes the copy menu would be displayed for a long press. Sometimes for a long press and lift up. Things like that.

2017-10-20 21:31 UTC, nathantannar4 approved these changes
Looks like a good feature we need

2017-10-20 21:44 UTC, SD10 commented
@nathantannar4 Were you able to test the gestures?Yes we definitely need it but it needs to be working properly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2017-10-21 02:35 UTC, nathantannar4 commented
@SD10 @Ganzolo I notice that the "Copy" prompt appears even when a long press is recognized on the AvatarView or anywhere else outside of the MessageLabel. Is this behavior we want?

Only other thing I see is if you long press a link such as an address, the "Copy" prompt appears before the notifier is sent that the user has tapped an address. I wonder if this can be prevented?

2017-10-21 09:26 UTC, SD10 commented
@nathantannar4 Thanks for the extra set of eyes. I definitely missed some of those. These are all valid points. Looks like we're going to have to look into this a little bit more.

It's a pretty important feature to have but easy enough for clients to implement on their own while we figure this out.

2017-10-23 08:09 UTC, Ganzolo commented
@SD10 @nathantannar4 
I looked today into this issue and I am afraid that we would need to use custom touch on a Cell level to prevent this behavior from happening.

I tried to make contentView transparent background or to assign a long press gesture to background of cell. But it does not work.

The other idea would be to respond false when this method is called only when the touch is not in the bubble area. However I didn't find a way to get the position of the touch from this method.

`func collectionView(_ collectionView: UICollectionView, shouldShowMenuForItemAt indexPath: IndexPath) -> Bool`

2017-10-26 16:27 UTC, cwalo commented
Sorry, just now getting to this. For your consideration - add a long press gesture recognizer to `MessageLabel` and either pass the gesture type along in the `MessageLabelDelegate` methods and/or have an additional `didLongPressMessageLabel` delegate method with a default implementation that displays the MenuController.

2017-10-26 23:29 UTC, SD10 commented
@cwalo Good suggestions. We may have to move this to the cell level as @Ganzolo mentioned. I'm going to be rewriting `MessageLabel` and then we can re-evaluate from there

2017-11-20 10:02 UTC, relaxsus commented
Hello! I can't call the menu with long press (copy, custom action...). when will this function be in MessageKit? Or help me, please, to write the right code. It was not the problem to call this menu on JSQ.

2017-11-20 14:14 UTC, SD10 commented
Hey @relaxsus,

You can remove the long press gesture from your MessageKit copy for now. Right now we require people to add copy/paste support themselves.

I agree this feature is something we should provide, but due to its ease of implementation outside of MessageKit, I’ve spent my time trying to resolve more serious issues. It’s on the roadmap though


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2018-01-10 22:50 UTC, nathantannar4 commented
#422

2018-01-10 22:50 UTC, closed without merging