Avatar
MessageKit/MessageKit pull request #26
Opened 2017-08-04 22:51 UTC by MacMeDan

Avatar class implementation. Added the ability to show initials on an avatar. Defaults to values for everything. Added Tests and a `Playground` so others can play with it.

2017-08-04 23:04 UTC, SD10 commented
@MacMeDan Thanks! I still have to review this but I only wish you could've submitted this to `v0.2.0` instead of `master` 😭 Any way we can do this? It may be better for me to review it first.

2017-08-04 23:36 UTC, SD10 commented on Sources/Avatar.swift
> +    open func roundCorners(by: CGFloat?) {
I think adding an internal parameter `radius` would be great 😃

2017-08-04 23:37 UTC, SD10 commented on Sources/Avatar.swift
> +        return imageView.image ?? UIImage()
Any specific reason why this doesn't return an optional?

2017-08-04 23:39 UTC, SD10 commented on Tests/AvatarTests.swift
> +        XCTAssertEqual(avatar.layer.cornerRadius, 0.0)
Looks like this is failing the tests on iOS 9+. Avatar has a default size of `30 x 30` resulting in a `cornerRadius` of `15.0`

2017-08-04 23:41 UTC, SD10 commented on .swiftlint.yml
> +- line_length
I do like the `trailing_whitespace` rule 🤔 Same with `line_length` but this is so trivial, let's leave it for now.

2017-08-04 23:42 UTC, SD10 requested changes
Great work, thank you for writing unit tests 😅
If you could please review the comments and fix the failing unit tests ❤️

2017-08-04 23:46 UTC, SD10 commented on Sources/Avatar.swift
> +open class Avatar: UIView {
Do you think `AvatarView` would be a better name? Allowing people to identify its a `UIView` subclass?

2017-08-05 04:28 UTC, SD10 commented
I'm just going to push this off to `v0.3.0`. Sorry for the nightmare of opening an closing PR's.

2017-08-06 02:08 UTC, MacMeDan commented on Sources/Avatar.swift
> +open class Avatar: UIView {
Ya that is what I had it called originally and then changed it for simplicity but I am not married to the idea I think I will go back to avatar view.

2017-08-06 02:15 UTC, MacMeDan commented on .swiftlint.yml
> +- line_length
So if you enable `trailing_whitespace` it throws a warning for blank line between methods. I like to separate each method with one empty line to make it easier to read. That is why i disabled it. 

![screen shot 2017-08-05 at 8 12 26 pm](https://user-images.githubusercontent.com/6182351/29000007-864e54f4-7a1a-11e7-951f-e98d777b42ff.png)

2017-08-06 02:23 UTC, SD10 commented on .swiftlint.yml
> +- line_length
You can still have empty lines but just no spaces on the empty line 🤔

2017-08-06 03:16 UTC, fbartho commented on .swiftlint.yml
> +- line_length
For what it's worth, there's an option in Xcode Preferences->Text Editing->Editing -- make sure the bottom of the two checkboxes in the following screenshot is checked: https://cl.ly/0d3C2E2B3x0A

2017-08-06 05:42 UTC, SD10 commented
Closing in favor of #31

2017-08-06 05:42 UTC, closed without merging