LocationMessageSnapshotOptions public
MessageKit/MessageKit pull request #452
Opened 2018-01-10 11:06 UTC by alessioarsuffi

What does this implement/fix? Explain your changes.
---------------------------------------------------
added public init and public to properties of
LocationMessageSnapshotOptions to prevent inaccessible compiler error  

Does this close any currently open issues?
------------------------------------------
#442

Any relevant logs, error output, etc?
-------------------------------------

Nothing

Any other comments?
-------------------
Nothing

Where has this been tested?
---------------------------
**Devices/Simulators:** iPhone SE

**iOS Version:** 11.2

**Swift Version:** 4

**MessageKit Version:** 0.12.1

2018-01-10 13:34 UTC, zhongwuzw requested changes

2018-01-10 13:34 UTC, zhongwuzw commented on Sources/Models/LocationMessageSnapshotOptions.swift
> +    public var showsBuildings = false
Please remove the initial value, because we have the default value in `initializer` method.

2018-01-10 13:34 UTC, zhongwuzw commented on Sources/Models/LocationMessageSnapshotOptions.swift
> +    public var showsPointsOfInterest = false
The same.

2018-01-10 13:34 UTC, zhongwuzw commented on Sources/Models/LocationMessageSnapshotOptions.swift
> +    public var span: MKCoordinateSpan = MKCoordinateSpan(latitudeDelta: 0, longitudeDelta: 0)
The same.

2018-01-10 13:34 UTC, zhongwuzw commented on Sources/Models/LocationMessageSnapshotOptions.swift
> +    public var scale: CGFloat = UIScreen.main.scale
The same.

2018-01-10 14:37 UTC, alessioarsuffi commented
@zhongwuzw done :)

2018-01-11 01:09 UTC, zhongwuzw approved these changes

2018-01-11 01:59 UTC, merged

2018-01-11 01:59 UTC, SD10 commented
Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley: