All-New ChatExample app
MessageKit/MessageKit pull request #803
Opened 2018-08-10 00:47 UTC by nathantannar4

Showcases how to do custom layouts, custom cells, embedded MessageViewControllers and typing indicators (when its released)

2018-08-10 00:48 UTC, nathantannar4 commented
Updated everything to be consistent with the latest MessageKit release and showed some examples for FAQ such as custom cells and embedded MessageViewControllers.

2018-08-10 01:37 UTC, zhongwuzw commented
@nathantannar4 Thanks for your great contribution, it has too much changes, let me take a breath. 😂

2018-08-10 02:12 UTC, nathantannar4 commented
@zhongwuzw changes aren't to the framework so it's not gonna break anything 🤣 just checkout the branch and run it. Mostly the same just refactored bit git sees all the project file changes as a lot

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2018-08-12 00:37 UTC, SD10 commented on .gitignore
> -Podfile.lock
We definitely should be checking in our lockfiles

2018-08-12 00:38 UTC, SD10 commented
Wonder what happened on CI 🤷‍♂️

2018-08-12 04:00 UTC, nathantannar4 commented
Seems to be that the VM on Circle has Cocoapods v1.3.1, but I have 1.5.3 locally. For reference the example app used to be built with Cocoapods 1.5.0. Updated the .yml that should hopefully fix this moving forward.

2018-08-12 05:04 UTC, nathantannar4 commented
Aight its working now

2018-08-14 07:03 UTC, zhongwuzw requested changes

2018-08-14 07:03 UTC, zhongwuzw commented on Example/Sources/View Controllers/ChatViewController.swift
> +            self?.messagesCollectionView.insertSections([messageList.count - 1])
`messageList` out of bounds check to prevent crash.

2018-08-14 07:03 UTC, zhongwuzw commented on Example/Sources/View Controllers/ChatViewController.swift
> +            self?.messagesCollectionView.reloadSections([messageList.count - 2])
What's the reason here to reload previous last section? 🤔

2018-08-14 07:03 UTC, zhongwuzw commented on Example/Sources/View Controllers/ChatViewController.swift
> +            self?.messagesCollectionView.scrollToBottom(animated: true)
Just a suggestion, can we make it not to `scrollToBottom` forcedly, because when I scroll the messages, I don't want the lists scroll to bottom suddenly. 😂 
If user scroll the lists manually, maybe we can disable this scroll to bottom behavior.

2018-08-14 07:03 UTC, zhongwuzw commented on Example/Sources/View Controllers/MessageContainerController.swift
> +//  Copyright © 2018 Nathan Tannar. All rights reserved.
Please change these copyright to `MessageKit`. 🤔

2018-08-14 08:32 UTC, nathantannar4 commented on Example/Sources/View Controllers/ChatViewController.swift
> +            self?.messagesCollectionView.scrollToBottom(animated: true)
This doesn't have to be a picture perfect example, more just trying to showcase available functionality to reduce common questions.

2018-08-14 08:33 UTC, nathantannar4 commented on Example/Sources/View Controllers/ChatViewController.swift
> +            self?.messagesCollectionView.reloadSections([messageList.count - 2])
Update previous sections footer visability or change the update the layout of the cell. See in action with the AdvancedExample

2018-08-14 08:35 UTC, nathantannar4 commented on Example/Sources/View Controllers/ChatViewController.swift
> +            self?.messagesCollectionView.insertSections([messageList.count - 1])
Sure

2018-08-15 15:02 UTC, zhongwuzw commented on Example/Sources/View Controllers/ChatViewController.swift
> +            self?.messagesCollectionView.reloadSections([messageList.count - 2])
Get it.

2018-08-21 21:30 UTC, nathantannar4 commented
@zhongwuzw Changes made. @SD10 We good to merge this in?

2018-08-21 22:36 UTC, SD10 commented
For the most part I'm okay with it because they're just example changes, I'd like to run it first and get some visuals 😢 It's just things are not stable at work and my open source work is suffering. We use MessageKit and it currently provides what we need as is

2018-08-21 23:13 UTC, nathantannar4 commented
Ya, its just the example. More to help reduce FAQs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2018-08-22 01:21 UTC, zhongwuzw approved these changes
LGTM

2018-08-22 02:21 UTC, merged