update to swift 4.2
MessageKit/MessageKit pull request #880
Opened 2018-09-27 13:20 UTC by moldovaniosif

What does this implement/fix? Explain your changes.
---------------------------------------------------
Update project to support swift 4.2.

Does this close any currently open issues?
------------------------------------------
No.

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Devices/Simulators:** iPhone 7, Simulator 7, X;

**iOS Version:** 12.0

**Swift Version:** 4.2

**MessageKit Version:** 1.0.0

2018-09-28 05:46 UTC, iceman201 requested changes

2018-09-28 05:46 UTC, iceman201 commented on Sources/Views/PlayButtonView.swift
> +    public let triangleView = UIView()
“open” is now simply “more public than public”, providing a very simple and clean model.

2018-09-28 21:20 UTC, aaronhuisinga commented
Definitely could used this merged. Unable to compile in Xcode 10 without the update to Swift 4.2.

2018-09-29 00:19 UTC, nathantannar4 commented
Tests failing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2018-09-29 00:26 UTC, brandon-haugen commented
@nathantannar4, it looks like this is only failing because it’s using Xcode 9 (which does not support Swift 4.2) instead of using Xcode 10 during CircleCI builds.

2018-09-29 00:39 UTC, nathantannar4 commented
Correct, the CircleCi file needs to be updated along with this PR. Also, target branch should be development not master @moldovaniosif. Please make sure your changes are rebased onto development as we already have pending changes 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2018-09-29 00:54 UTC, brandon-haugen commented
@nathantannar4 thank you! I wasn’t sure what need to be done to update Circle CI to use the updated version of Xcode. I meant to add that in my first comment since others might not be familiar with Circle CI either.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2018-09-29 20:28 UTC, SD10 commented
Closing in favor of #883. @moldovaniosif appreciate you taking the time to do this 💪 Sent you an invite to the MessageKit org

2018-09-29 20:28 UTC, closed without merging