A workaround solution for the render issue with MessageInputBar
MessageKit/MessageKit pull request #99
Opened 2017-09-03 19:44 UTC by nathantannar4

It seems as though when using a UINavigationController there is an issue with the rendering of an inputAccessoryView. This workaround creates a copy during the animation and then deletes it.

2017-09-03 23:00 UTC, SD10 commented on Sources/InputTextView.swift
> +        setup()
@nathantannar4 Is this part of the workaround? There was a problem with unarchiving?

2017-09-03 23:05 UTC, SD10 commented on Sources/MessagesViewController.swift
> +    private var messageInputBarCopy: MessageInputBar?
Can we add a small comment above this explaning why we have it?

2017-09-03 23:06 UTC, SD10 commented on Sources/MessagesViewController.swift
> +        copy.addConstraints(nil, left: view.leftAnchor, bottom: view.bottomAnchor, right: view.rightAnchor, topConstant: 0, leftConstant: 0, bottomConstant: 0, rightConstant: 0, widthConstant: 0, hei
Mind splitting this up onto multiple lines?

2017-09-03 23:09 UTC, SD10 commented on Sources/MessagesViewController.swift
> +        messageInputBarCopy = nil
Can you put these two things in its own private method `removeMessageInputBarCopy()`?

2017-09-03 23:09 UTC, SD10 requested changes
@nathantannar4 If you could just take care of a few nitty things. Mainly I want to add that comment for why we are doing it. One line should suffice

2017-09-04 13:57 UTC, SD10 commented
@nathantannar4 I'm taking care of these now 👍

2017-09-04 14:08 UTC, SD10 approved these changes

2017-09-04 16:52 UTC, merged

2017-09-04 16:53 UTC, nathantannar4 commented
Thanks @SD10, sorry I didn't have a chance to get to this yesterday